---
- name: install initial packages on all boxes
  hosts: servers
  #remote_user: ansible 
  become: yes
  
  tasks:
    - name: install chrony
      yum:
    
        name: chrony
        state: latest

    - name: configure chrony
      template:
        src: /home/ansible/ANSIBLE/NTP/chrony.server.j2
        dest: /etc/chrony.conf
  

    - name: start and anable chronyd
      service:
        name: chronyd
        state: started
        enabled: yes


