---
- name: install initial packages on all boxes
  hosts: all
  remote_user: ec2-user 
  become: 'yes'
  become_user: root
  
  tasks:
    - name: install chrony
      yum:
    
        name: chrony
        state: latest

    - name: configure chrony
      template:
        src: /home/ansible/ANSIBLE/NTP/chrony.server.j2
        dest: /etc/chrony.conf
  

    - name: start and anable chronyd
      service:
        name: chronyd
        state: started
        enabled: yes


C:\Users\dave0\OneDrive\Documents\GitHub\ANSIBLE\NTP\master.yml